NumPy-Numerical Python

Advantages of Numpy Arrays:

    1. Allows several Mathematical Operations
    2. Faster operations

In [1]:
import numpy as np

List vs Numpy - Time Taken

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0


In [5]:
np_array = np.array([i for i in range (10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0


Numpy Arrays

In [6]:
# list
list1 = [1, 2, 3, 4, 5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [7]:
np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
# creating a 1 dim array
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [9]:
a.shape

(4,)

In [10]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b.shape

(2, 4)

In [14]:
c = np.array([(1),(2),(3),(4)])
print(c)

[1 2 3 4]


In [15]:
c.shape

(4,)

In [17]:
d = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(d)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initaial Placeholders in numpy arrays

In [18]:
# create a nummpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
# create a numpy aray of ones
y = np.ones((3, 3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# array of a particular value
z = np.full((5, 4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [21]:
# create an identify matrix
a = np.eye((4))
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.86848498 0.10049077 0.27628723 0.21029888]
 [0.39161619 0.94234791 0.62081782 0.24300125]
 [0.42238086 0.71329101 0.72666114 0.74938891]]


In [23]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[41 36 43 63 94]
 [21 15 78 81 29]
 [75 36 32 81 74]]


In [26]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [27]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [29]:
# convert a list to a nummpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array 

In [30]:
c = np.random.randint(10,90,(5,5))
print(c)

[[28 87 85 25 11]
 [17 67 52 78 52]
 [54 30 42 51 64]
 [38 19 57 39 85]
 [59 85 76 12 51]]


In [32]:
# array dimension
print(c.shape)

(5, 5)


In [33]:
# number of dimension
print(c.ndim)

2


In [34]:
# number of elements in a array
print(c.size)

25


In [35]:
# checking the data type of the values in the array
print(c.dtype)

int32


Mathematical operations on a np array 

In [39]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatenate or joint two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [46]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [43]:
print(a)
print(b)

[[1 2 2]
 [7 9 2]
 [7 3 7]]
[[12 12 11]
 [10 14 17]
 [14 18 17]]


In [47]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[27 21 26]
 [15 19 12]
 [12 18 19]]
[[-11 -13 -12]
 [ -5 -13 -12]
 [-10 -14  -5]]
[[152  68 133]
 [ 50  48   0]
 [ 11  32  84]]
[[0.42105263 0.23529412 0.36842105]
 [0.5        0.1875     0.        ]
 [0.09090909 0.125      0.58333333]]


In [50]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [53]:
print(a)
print(b)

[[9 4 0]
 [3 9 2]
 [0 1 0]]
[[16 18 12]
 [13 17 16]
 [17 17 16]]


In [54]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[25 22 12]
 [16 26 18]
 [17 18 16]]
[[ -7 -14 -12]
 [-10  -8 -14]
 [-17 -16 -16]]
[[144  72   0]
 [ 39 153  32]
 [  0  17   0]]
[[0.5625     0.22222222 0.        ]
 [0.23076923 0.52941176 0.125     ]
 [0.         0.05882353 0.        ]]


Array Manipulation

In [55]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 0 1]
 [4 6 2]]
(2, 3)


In [56]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[5 4]
 [0 6]
 [1 2]]
(3, 2)


In [57]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 7 3]
 [2 3 4]]
(2, 3)


In [58]:
trans2 =  array.T
print(trans2)
print(trans2.shape)

[[7 2]
 [7 3]
 [3 4]]
(3, 2)


In [59]:
# Reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[6 6 2]
 [2 1 3]]
(2, 3)


In [60]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[6 6]
 [2 2]
 [1 3]]
(3, 2)
